---

- name: Install apache2-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: false
  with_items: apache2_packages

- name: Divert apache2.conf
  command: dpkg-divert --quiet --local --divert /etc/apache2/apache2.conf.dpkg-divert
           --rename /etc/apache2/apache2.conf creates=/etc/apache2/apache2.conf.dpkg-divert

- name: Create main apache2 configuration
  template:
    src: 'etc/apache2/apache2.conf.j2'
    dest: '/etc/apache2/apache2.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Check apache2 and reload' ]
