---

- name: Install apache2-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: false
  with_items: apache2_packages

- name: Divert apache2.conf
  command: dpkg-divert --quiet --local --divert /etc/apache2/apache2.conf.dpkg-divert
           --rename /etc/apache2/apache2.conf creates=/etc/apache2/apache2.conf.dpkg-divert

- name: Create main apache2 configuration
  template:
    src: 'etc/apache2/apache2.conf.j2'
    dest: '/etc/apache2/apache2.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Check apache2 and reload' ]

- name: Create custom directory
  file:
    path: '/etc/apache2/{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items: [ 'conf.d', 'vhosts.d' ]

- name: Delete unused directories
  file:
    path: '/etc/apache2/{{ item }}'
    state: 'absent'
  with_items: [ 'conf-available', 'conf-enabled', 'sites-available', 'sites-enabled' ]

- name: Create custom configurations
  template:
    src: 'etc/apache2/conf.d/{{ item }}.j2'
    dest: '/etc/apache2/conf.d/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: apache2_configs
  notify: [ 'Check apache2 and reload' ]

- name: Get list of apache2 enabled mods
  shell: 'ls /etc/apache2/mods-enabled | cut -d. -f1 | uniq'
  register: apache2_register_enabled_mods
  changed_when: false

- name: Enable apache2 mods
  shell: /usr/sbin/a2enmod --quiet {{ item }}
  with_items: ((apache2_mods_enable|d([])) +
               (apache2_mods_enable_group|d([])) +
               (apache2_mods_enable_host|d([]))) |
              difference(apache2_register_enabled_mods.stdout_lines)
  notify: [ 'Check apache2 and reload' ]

- name: Disable apache2 mods
  shell: /usr/sbin/a2dismod --quiet {{ item }}
  with_items: ((apache2_mods_disable|d([])) +
               (apache2_mods_disable_group|d([])) +
               (apache2_mods_disable_host|d([]))) |
              difference(((apache2_mods_disable|d([])) +
                          (apache2_mods_disable_group|d([])) +
                          (apache2_mods_disable_host|d([]))) |
                         difference(apache2_register_enabled_mods.stdout_lines))
  notify: [ 'Check apache2 and reload' ]

- name: Create vhosts
  template:
    src: 'etc/apache2/vhosts.d/{{ item.type|d("default") }}.conf.j2'
    dest: '/etc/apache2/vhosts.d/{{ item.name }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: apache2_vhosts
  when: apache2_vhosts is defined and apache2_vhosts
  notify: [ 'Check apache2 and reload' ]
